name: Tests

on: 
  push:
    branches:
      - main  # ou o nome do branch principal do seu repositório
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ze/requirements_dev.txt

      - name: Run tests
        run: |
          pytest ze/tests/
